---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.


Adam Zhu was here. This is a line from RSTUDIO

This is a line from RStudio - ANNA WAS HERE

Grace

Adam's Summary: It was a struggle.

I wasn’t connected to GitHub initially, so I had to manually add the repository to my project by copying and pasting the link. I also struggled to sync my work with my lab mates. Eventually, I realized that I needed to make changes, save, commit, push, and then pull in that order to avoid any issues.

Anna Summary: 
I first had to install github correctly. I did this by downloading a package. My next problem was that I had to configure my git ID. I did this by using my counsel and writing the commands "git config --global Anna" and "git config --afedie@iastate.edu". One last problem I had was when typing "This is a line from RSTUDIO". I fist had to save and commit my lines and then merge it together with Adam's and Grace's changes included. I did this by combining our lines and then Pushing the data out. Then lastly if someone else made changes I pulled it into the file.
